

export const todosActions = {
    GET_TODO_REQUEST: "GET_TODO_REQUEST",
    GET_TODO_SUCCESS: "GET_TODO_SUCCESS",
    GET_TODO_FAILURE: "GET_TODO_FAILURE",

    ADD_TODO_REQUEST: "ADD_TODO_REQUEST",
    ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
    ADD_TODO_FAILURE: "ADD_TODO_FAILURE",

    DETAILS_TODO_REQUEST: "DETAILS_TODO_REQUEST",
    DETAILS_TODO_SUCCESS: "DETAILS_TODO_SUCCESS",
    DETAILS_TODO_FAILURE: "DETAILS_TODO_FAILURE",

    GET_COMPLETED_REQUEST: "GET_COMPLETED_REQUEST",
    GET_COMPLETED_SUCCESS: "GET_COMPLETED_SUCCESS",
    GET_COMPLETED_FAILURE: "GET_COMPLETED_FAILURE",

    PATCH_TODO_TOGGLE: "PATCH_TODO_TOGGLE",
};