export const FETCH_TODO_REQUEST="FETCH_TODO_REQUEST";
export const FETCH_TODO_SUCCESS="FETCH_TODO_SUCCESS";
export const FETCH_TODO_FAILURE="FETCH_TODO_FAILURE";


export const ADD_FETCH_TODO_REQUEST="ADD_FETCH_TODO_REQUEST";
export const ADD_FETCH_TODO_SUCCESS="ADD_FETCH_TODO_SUCCESS";
export const ADD_FETCH_TODO_FAILURE="ADD_FETCH_TODO_FAILURE";